# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "金算子"
email: aug_88@163.com
description: >- # this means to ignore newlines until "baseurl:"
  金算子是一款全面的金融计算应用，为您提供一系列强大的工具，助您轻松应对各种金融场景。不论是投资计算、贷款规划、还是工资明细，金算子都是您财务规划的理想选择。
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  Jyhu
permalink: '/:year/:title'

# Build settings
theme: bay_jekyll_theme
plugins:
  - jekyll-feed

header:
  pages:
    - name: Home
      slug: /     # <-- index.md
    - name: Docs  # <-- blog.md
    
footer:
  show_powered_by: false
  contact:
    - name: Email
      value: aug_88@163.com
      link: mailto:aug_88@163.com
#    - name: WeChat
#      value: YourWeChatUsername
#      link: "#"
  follow:
#    - name: Twitter
#      link: http://twitter.com/YourTwitterUsername
#      username: "@YourTwitterUsername"
#    - name: Facebook
#      link: http://facebook.com/YourFacebookUsername
#    - name: LinkedIn
#      link: http://linkedin.com/in/YourLinkedInUsername
    - name: GitHub
      link: http://github.com/JyHu
#    - name: Dribbble
#      link: https://dribbble.com/YourDribbbleUsername
#    - name: Weibo
#      link: http://weibo.com/u/YourWeiboUsername
#    - name: RSS
#      link: /feed.xml

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
